language: ruby
before_install:
  - ./spec/travis_build.sh
  - bundle install
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - rbx-head
notifications:
  email: false
branches:
  only:
    - master
    - development
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head