language: ruby
before_install:
  - sh -c 'spec/build_webp_travis.sh'
  - bundle install
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - ruby-head
  - jruby-head
notifications:
  email: false
branches:
  only:
    - master
    - development
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head